baseurl = "https://www.metachris.dev"
title = "Chris Hager"

theme = "mc2020"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 25
canonifyurls = true

# Syntax highlighting
# - https://gohugo.io/content-management/syntax-highlighting
# - https://gohugo.io/quick-reference/syntax-highlighting-styles
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

summaryLength = 70

# enableGitInfo = true
enableEmoji = true

[permalinks]
posts = "/:year/:month/:title/"

[params]
author = "Chris Hager"
info = "Builder, Maker, Engineer"
description = "Builder, Maker, Engineer"
images = ["images/profile2-round.png"]   # OG & Twitter meta tags on homepage
avatarurl = "images/profile2-round.png"

favicon_32 = "images/favicon-32px.png"
favicon_16 = "images/favicon-16px.png"

# footercontent = "Nice going."

dateformat = "January 2, 2006"

hideCopyright = true
hideCredits = false
since = 2016

rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorscheme = "auto"

# Series see also post count
maxSeeAlsoItems = 5

# Custom CSS
custom_css = []

# Custom JS
custom_js = ['js/custom.js']

# Custom SCSS
custom_scss = ["scss/custom.scss"]

[params.utteranc]
repo = "metachris/metachris.dev-comments"
theme = "preferred-color-scheme"
issueTerm = "og:title"

[markup]
[markup.tableOfContents]
endLevel = 3

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[languages]
[languages.en]
languagename = "English"

[languages.en.menu]
[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"
